POST http://localhost:3000/api/services
Content-Type: application/json

{ //alterar objeto jason do service quando for completado
    "name": "zé boceta",
    "description": "ave maria man, eh o ze buocecta"
}

###

// Method get all
GET http://localhost:3000/api/services


###

POST http://localhost:3000/api/services
Content-Type: application/json

{
    "name": "matuê",
    "description": "Show do matuê",
    "image": "teste imagem",
    "status": true,
    "members": {"_id": "65f057c8a59c6548d83b2e85"
}}

###

// Method get with id

GET http://localhost:3000/api/services/65f057c8a59c6548d83b2e85


### 

// Method delete with id

DELETE  http://localhost:3000/api/services/65f057c8a59c6548d83b2e85

### 

PUT http://localhost:3000/api/services/65f08bc0dcfa32a11184f24d
Content-Type: application/json

{
"name": "matuê",
"description": "Show do matuê",
"image": "https://i.ytimg.com/vi/G5xFRcb5lA8/maxresdefault.jpg",
"status": true
}